AllCops:
  NewCops: enable
  Exclude:
    - bin/**
Lint/MissingSuper:
  Enabled: true
  Exclude:
    - app/views/ui_components/*.rb
Rails/I18nLocaleTexts:
  Enabled: false
inherit_gem:
  rubocop-shopify: rubocop.yml
inherit_from: .rubocop.sorbet.yml
require:
  - rubocop-sorbet
  - rubocop-rails
