# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::Component`.
# Please instead update this file by running `bin/tapioca dsl Icon::Component`.

class Icon::Component
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
